[tool.black]
line-length = 79
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | migrations
)/
'''

[tool.ruff]
line-length = 79
target-version = "py311"
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "migrations",
    "__pycache__",
    "manage.py",
]
select = ["E", "F", "W", "I"]
ignore = []
fixable = ["A", "B", "C", "D", "E", "F", "W", "I"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.isort]
known-first-party = ["config"]
